Improve categories with measures
datalab-mi/Basegun pull request #416
Opened 2024-04-07 22:50 UTC by thomashbrnrd

2024-04-08 14:35 UTC, ClemGerard approved these changes

2024-04-09 08:58 UTC, leihuayi requested changes
Two big issues, which actually should have been dealt with in https://github.com/datalab-mi/Basegun/pull/395/
- in the measurement, the backend should launch the measurement algo **only if the label in within some typologies** 
- the unit tests are **not well-thought**. They do **not test well all the possibilities of the algorithms**. They should be designed with the algorithm owners @AurelienmartW .

2024-04-11 15:09 UTC, leihuayi approved these changes

2024-04-11 15:10 UTC, leihuayi commented
Issue with armes d'alarm which should be split between revolvers and pistolets semi-auto, to fix in another PR

2024-04-11 15:20 UTC, thomashbrnrd commented on backend/src/config.py
> +]
`typology.py`will go in the basegun-ml repository

2024-04-11 15:20 UTC, merged