enhancement about page
datalab-mi/Basegun pull request #84
Opened 2022-09-26 09:10 UTC by Carolinedanslesnuages

fix #79

2022-09-26 14:07 UTC, leihuayi requested changes
Hello, je vois que ta branche n'a pas la dernière version de Develop. Peux-tu pull et merge dans ta branche s'il te plaît ?
Ayant des petits problèmes de config avec mon noemi je ne peux pas tester ton travail ajd, je pense pouvoir regarder demain !

2022-09-26 14:16 UTC, Carolinedanslesnuages commented
Voilà! j'ai rebase ma branch sur develop

2022-09-26 21:38 UTC, leihuayi requested changes

2022-09-26 21:38 UTC, leihuayi commented on frontend/src/views/text_content/AboutTextContent.vue
> +    .img {
En affichage mobile, les logos de la DNUM et de la police sont hors-champ

2022-09-26 21:38 UTC, leihuayi commented on frontend/src/views/text_content/AboutTextContent.vue
> +            en collaboration avec le SCAE , la police nationale et la gendarmerie.</p>
Pourrais-tu changer par le nouveau texte s'il te plaît:
- mettre un lien vers https://eig.etalab.gouv.fr/defis/basegun/ sur "programme Entrepreneurs d’Intérêt Général"
- contenu du nouveau texte:
```
Le projet a été initié en 2021 dans le contexte du programme <a>Entrepreneurs d’Intérêt Général</a>. 
Il continue actuellement sous la collaboration de 4 entités du Ministère de l'Intérieur:
- Le Datalab de la Direction du Numérique, pour le pilotage du projet et le développement de l'application;
- Le Service Central des Armes et Explosifs, pour un contrôle régulier via la connaissance métier des armes à feu;
- La Police et la Gendarmerie, pour des tests et suivis ponctuels de l'application.
 ```

2022-09-27 14:33 UTC, leihuayi approved these changes
all good :)

2022-09-27 14:33 UTC, merged